name: ci

on:
  push:
    branches:
      - 'main'
    paths:
      - backend/**

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: ghcr.io/webmastercamp/${{ github.event.repository.name }}-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - 
        name: Deploy
        uses: WebmasterCamp/deploy-action@main
        with:
          image: ghcr.io/webmastercamp/${{ github.event.repository.name }}-backend@${{ steps.build-and-push.outputs.digest }}
          port: 3000
