name: ci

on:
  push:
    branches:
      - 'main'

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  docker:
    name: ${{ matrix.buildTarget }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        buildTarget: [frontend, backend]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{ matrix.buildTarget }}"
          push: true
          tags: ghcr.io/webmastercamp/${{ github.event.repository.name }}-${{ matrix.buildTarget }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy
        uses: WebmasterCamp/deploy-action@main
        with:
          image: ghcr.io/webmastercamp/${{ github.event.repository.name }}-${{ matrix.buildTarget }}@${{ steps.build-and-push.outputs.digest }}
          deploymentName: ${{ matrix.buildTarget }}
          port: 3000
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
